name: Worflow test
on: push 
env:
  ARTIFACT: myArtifact
jobs:
  job1:
    name: first job 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT }}
          path: .


